"""Modular interactive mapper package for map loading, planning, and robot control."""

from .config import (
    AUTO_EXECUTE_PATH,
    CAMERA_ID,
    CAMERA_TYPE,
    CONNECT_ROBOT_ON_START,
    IMU_TYPE,
    LANDMARKS_FILE,
    LANDMARK_SETUP_MODE,
    LANDMARK_SETUP_WINDOW_NAME,
    MAP_FILE,
    MULTI_ROBOT_CLOSE_LOOP,
    MULTI_ROBOT_ESTIMATED_SPEED_MPS,
    MULTI_ROBOT_MIN_OBSTACLE_DISTANCE_PX,
    MULTI_ROBOT_MIN_PATH_CLOSENESS_PX,
    MULTI_ROBOT_MIN_SEGMENT_POINTS,
    MULTI_ROBOT_OUTPUT_IMAGE,
    MULTI_ROBOT_PATROL_MODE,
    MULTI_ROBOT_SHOW_WINDOW,
    MULTI_ROBOT_STARTS,
    MULTI_ROBOT_SWEEP_STEP_PX,
    MIN_WALL_DISTANCE_M,
    PHONE_IP,
    POLL_SENSORS_IN_LOOP,
    RESOLUTION_M_PER_PX,
    ROBOT_IP,
    RUN_WAIT_MS,
    SPEED_MULTIPLIER,
    START_HEADING_DEG,
    START_X,
    START_Y,
    USE_FUSED_INTERNAL_YAW,
    WINDOW_NAME,
)
from .controller import InteractiveMapper
from .landmark_setup import LandmarkSetupSession, run_landmark_setup_session
from .multi_robot_sections import (
    MultiRobotMapPartitioner,
    PatrolQualityMetrics,
    RobotSection,
    SectionPatrolPlanner,
    SectionVisualizer,
    compute_patrol_quality_metrics,
    draw_route,
    partition_map_and_plan_patrols,
)
from .types import SensorCallback, SensorSnapshot

__all__ = [
    "AUTO_EXECUTE_PATH",
    "CAMERA_ID",
    "CAMERA_TYPE",
    "CONNECT_ROBOT_ON_START",
    "IMU_TYPE",
    "LANDMARKS_FILE",
    "LANDMARK_SETUP_MODE",
    "LANDMARK_SETUP_WINDOW_NAME",
    "MULTI_ROBOT_CLOSE_LOOP",
    "MULTI_ROBOT_ESTIMATED_SPEED_MPS",
    "MULTI_ROBOT_MIN_OBSTACLE_DISTANCE_PX",
    "MULTI_ROBOT_MIN_PATH_CLOSENESS_PX",
    "MULTI_ROBOT_MIN_SEGMENT_POINTS",
    "MULTI_ROBOT_OUTPUT_IMAGE",
    "MULTI_ROBOT_PATROL_MODE",
    "MULTI_ROBOT_SHOW_WINDOW",
    "MULTI_ROBOT_STARTS",
    "MULTI_ROBOT_SWEEP_STEP_PX",
    "MultiRobotMapPartitioner",
    "InteractiveMapper",
    "LandmarkSetupSession",
    "MAP_FILE",
    "MIN_WALL_DISTANCE_M",
    "PatrolQualityMetrics",
    "PHONE_IP",
    "POLL_SENSORS_IN_LOOP",
    "RESOLUTION_M_PER_PX",
    "RobotSection",
    "ROBOT_IP",
    "RUN_WAIT_MS",
    "SPEED_MULTIPLIER",
    "START_HEADING_DEG",
    "START_X",
    "START_Y",
    "SectionPatrolPlanner",
    "SectionVisualizer",
    "SensorCallback",
    "SensorSnapshot",
    "compute_patrol_quality_metrics",
    "draw_route",
    "partition_map_and_plan_patrols",
    "run_landmark_setup_session",
    "USE_FUSED_INTERNAL_YAW",
    "WINDOW_NAME",
]
